spring:
  datasource:
    url: jdbc:mysql://118.89.49.148:3306/bx_travels?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: Banxing@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      test-while-idle: true
      validation-query: select 1