spring:
  datasource:
    url: jdbc:mysql://139.199.72.118:3306/bx_travels?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: "@bx123456"
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      test-while-idle: true
      validation-query: select 1