server:
  port: 8091
  servlet:
    context-path: /bx
spring:
  profiles:
    active: prod
  #thymeleaf Start
  thymeleaf:
    #非严格检查
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
      #开发时关闭缓存(设置为false),不然没法看到实时页面
    cache: true
    prefix: classpath:/templates/
    suffix: .html
    #thymeleaf End

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
##该配置节点为独立节点
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.bx.touristsinfo.model

